name: Foo

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  foo:
    runs-on: ubuntu-latest

    steps:
      - name: Show event
        run: echo "Event:${{ github.event }}"
      - name: Show release event
        run: echo "Release event:${{ github.event.release }}"
